name: SSh remote deploy
on:
  registry_package:
    types: [published]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Remote deploy
      uses: appleboy/ssh-action@master
      env:
        DOCKERUSERNAME: ${{ github.actor }}
        DOCKERPASSWORD: ${{ secrets.CR_PAT }}
        NAME: hnit-acm-web-v2
        CNAME: docker.pkg.github.com/${{ github.repository }}/hnit-acm-web-v2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: DOCKERUSERNAME,DOCKERPASSWORD,NAME,CNAME
        script: |
          echo "$DOCKERUSERNAME,$NAME,$CNAME"
          docker login https://docker.pkg.github.com -u $DOCKERUSERNAME -p $DOCKERPASSWORD
          docker pull $CNAME
          docker rm -f $NAME | true
          docker run --net=host --name $NAME -d $CNAME
